name: "Org1 Client"
version: "1.0"

client:
  organization: Org1
  credentialStore:
    path: "../crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcert/"
    cryptoStore:
      path: "../crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcert/"